export type ShopItem = {
  id: string;
  name: string;
  cost: number;
  requiredLevel: number;
  category: "org_chart" | "power_upgrade";
  effect: string;
  expectedValuePerThousandInputs?: number;
};

export const shopItems: ShopItem[] = [
  {
    id: "royal_contract",
    name: "Royal Contract",
    cost: 100,
    requiredLevel: 2,
    category: "org_chart",
    effect:
      "Pay 100 Influence to bribe a court official for a royal contract. This makes you the marketing manager for the Aethernet royal court.",
  },
  {
    id: "crumpled_court_onboarding_manual",
    name: "Tiny Royal Reminder Kit",
    cost: 100,
    requiredLevel: 3,
    category: "power_upgrade",
    effect: "0.75% chance per input to publish a tiny royal reminder worth 25 Influence.",
    expectedValuePerThousandInputs: 188,
  },
  {
    id: "bottomless_court_coffee_mug",
    name: "Bottomless Court Coffee Mug",
    cost: 250,
    requiredLevel: 6,
    category: "power_upgrade",
    effect: "0.60% chance per input to fuel a late-night court campaign worth 50 Influence.",
    expectedValuePerThousandInputs: 300,
  },
  {
    id: "royal_suggestion_box_of_destiny",
    name: "Royal Suggestion Box of Destiny",
    cost: 500,
    requiredLevel: 9,
    category: "power_upgrade",
    effect: "0.50% chance per input to discover a court-approved idea worth 100 Influence.",
    expectedValuePerThousandInputs: 500,
  },
  {
    id: "royal_crier_app_subscription",
    name: "Royal Crier App Subscription",
    cost: 900,
    requiredLevel: 12,
    category: "power_upgrade",
    effect: "0.40% chance per input to trigger a royal bulletin worth 150 Influence.",
    expectedValuePerThousandInputs: 600,
  },
  {
    id: "ledger_of_courtly_accounting",
    name: "Ledger of Courtly Accounting",
    cost: 1_500,
    requiredLevel: 15,
    category: "power_upgrade",
    effect: "0.32% chance per input to reclassify a campaign win worth 250 Influence.",
    expectedValuePerThousandInputs: 800,
  },
  {
    id: "crystal_audience_analytics_orb",
    name: "Crystal Audience Analytics Orb",
    cost: 2_500,
    requiredLevel: 18,
    category: "power_upgrade",
    effect: "0.26% chance per input to discover an audience trend worth 400 Influence.",
    expectedValuePerThousandInputs: 1_040,
  },
  {
    id: "enchanted_press_release_quill",
    name: "Enchanted Press Release Quill",
    cost: 4_000,
    requiredLevel: 21,
    category: "power_upgrade",
    effect: "0.22% chance per input to draft a viral royal post worth 600 Influence.",
    expectedValuePerThousandInputs: 1_320,
  },
  {
    id: "royal_mimic_stamp",
    name: "Royal Mimic Stamp",
    cost: 6_000,
    requiredLevel: 24,
    category: "power_upgrade",
    effect: "0.18% chance per input to stamp a royal duplicate worth 900 Influence.",
    expectedValuePerThousandInputs: 1_620,
  },
  {
    id: "royal_messaging_handbook_revised_edition",
    name: "Royal Messaging Handbook, Revised Edition",
    cost: 8_500,
    requiredLevel: 27,
    category: "power_upgrade",
    effect: "0.15% chance per input to approve revised messaging worth 1,200 Influence.",
    expectedValuePerThousandInputs: 1_800,
  },
  {
    id: "court_newsletter_press",
    name: "Court Newsletter Press",
    cost: 12_000,
    requiredLevel: 30,
    category: "power_upgrade",
    effect: "0.12% chance per input to release a court newsletter worth 1,800 Influence.",
    expectedValuePerThousandInputs: 2_160,
  },
  {
    id: "goblin_outreach_playbook",
    name: "Goblin Outreach Playbook",
    cost: 17_000,
    requiredLevel: 33,
    category: "power_upgrade",
    effect: "0.10% chance per input to launch a royal outreach campaign worth 2,500 Influence.",
    expectedValuePerThousandInputs: 2_500,
  },
  {
    id: "royal_quest_board",
    name: "Royal Quest Board",
    cost: 23_000,
    requiredLevel: 36,
    category: "power_upgrade",
    effect: "0.08% chance per input to complete a royal contract worth 3,500 Influence.",
    expectedValuePerThousandInputs: 2_800,
  },
  {
    id: "arcane_audience_survey_scrolls",
    name: "Arcane Audience Survey Scrolls",
    cost: 30_000,
    requiredLevel: 39,
    category: "power_upgrade",
    effect: "0.07% chance per input to uncover audience sentiment worth 4,500 Influence.",
    expectedValuePerThousandInputs: 3_150,
  },
  {
    id: "court_recruitment_poster_set",
    name: "Court Recruitment Poster Set",
    cost: 40_000,
    requiredLevel: 42,
    category: "power_upgrade",
    effect: "0.06% chance per input to recruit royal advocates worth 6,000 Influence.",
    expectedValuePerThousandInputs: 3_600,
  },
  {
    id: "royal_courier_satchel",
    name: "Royal Courier Satchel",
    cost: 55_000,
    requiredLevel: 45,
    category: "power_upgrade",
    effect: "0.05% chance per input to receive a royal decree worth 8,000 Influence.",
    expectedValuePerThousandInputs: 4_000,
  },
  {
    id: "lute_of_royal_ballads",
    name: "Lute of Royal Ballads",
    cost: 75_000,
    requiredLevel: 48,
    category: "power_upgrade",
    effect: "0.04% chance per input to start a royal hype train worth 12,000 Influence.",
    expectedValuePerThousandInputs: 4_800,
  },
  {
    id: "royal_sponsorship_contract",
    name: "Royal Sponsorship Contract",
    cost: 100_000,
    requiredLevel: 51,
    category: "power_upgrade",
    effect: "0.035% chance per input to secure a royal sponsorship worth 16,000 Influence.",
    expectedValuePerThousandInputs: 5_600,
  },
  {
    id: "runic_royal_printing_press",
    name: "Runic Royal Printing Press",
    cost: 130_000,
    requiredLevel: 54,
    category: "power_upgrade",
    effect: "0.03% chance per input to print a runic campaign worth 22,000 Influence.",
    expectedValuePerThousandInputs: 6_600,
  },
  {
    id: "dragon_egg_aethernet_cluster",
    name: "Dragon Egg Aethernet Cluster",
    cost: 170_000,
    requiredLevel: 57,
    category: "power_upgrade",
    effect: "0.026% chance per input to hatch an Aethernet surge worth 30,000 Influence.",
    expectedValuePerThousandInputs: 7_800,
  },
  {
    id: "tome_of_royal_memes",
    name: "Tome of Royal Memes",
    cost: 220_000,
    requiredLevel: 60,
    category: "power_upgrade",
    effect: "0.022% chance per input to create a court meme worth 40,000 Influence.",
    expectedValuePerThousandInputs: 8_800,
  },
  {
    id: "royal_public_relations_handbook",
    name: "Royal Public Relations Handbook",
    cost: 280_000,
    requiredLevel: 63,
    category: "power_upgrade",
    effect: "0.019% chance per input to avert a royal PR crisis worth 55,000 Influence.",
    expectedValuePerThousandInputs: 10_450,
  },
  {
    id: "patent_pending_campaign_spellbook",
    name: "Patent Pending Campaign Spellbook",
    cost: 350_000,
    requiredLevel: 66,
    category: "power_upgrade",
    effect: "0.016% chance per input to invent a royal trend worth 75,000 Influence.",
    expectedValuePerThousandInputs: 12_000,
  },
  {
    id: "arcane_audience_research_journal",
    name: "Arcane Audience Research Journal",
    cost: 450_000,
    requiredLevel: 69,
    category: "power_upgrade",
    effect: "0.014% chance per input to discover an audience breakthrough worth 95,000 Influence.",
    expectedValuePerThousandInputs: 13_300,
  },
  {
    id: "royal_aetherwave_broadcast_tower",
    name: "Royal Aetherwave Broadcast Tower",
    cost: 575_000,
    requiredLevel: 72,
    category: "power_upgrade",
    effect: "0.012% chance per input to hit an Aetherwave broadcast worth 125,000 Influence.",
    expectedValuePerThousandInputs: 15_000,
  },
  {
    id: "royal_expedition_contract_ledger",
    name: "Royal Expedition Contract Ledger",
    cost: 725_000,
    requiredLevel: 75,
    category: "power_upgrade",
    effect: "0.010% chance per input to receive a royal expedition report worth 170,000 Influence.",
    expectedValuePerThousandInputs: 17_000,
  },
  {
    id: "dragon_endorsed_royal_campaign",
    name: "Dragon-Endorsed Royal Campaign",
    cost: 900_000,
    requiredLevel: 78,
    category: "power_upgrade",
    effect: "0.009% chance per input to receive a dragon endorsement for the crown worth 220,000 Influence.",
    expectedValuePerThousandInputs: 19_800,
  },
  {
    id: "royal_census_crystal",
    name: "Royal Census Crystal",
    cost: 1_100_000,
    requiredLevel: 81,
    category: "power_upgrade",
    effect: "0.008% chance per input to receive a kingdom audience report worth 280,000 Influence.",
    expectedValuePerThousandInputs: 22_400,
  },
  {
    id: "royal_prophecy_engine",
    name: "Royal Prophecy Engine",
    cost: 1_350_000,
    requiredLevel: 84,
    category: "power_upgrade",
    effect: "0.007% chance per input to trigger a royal prophecy worth 360,000 Influence.",
    expectedValuePerThousandInputs: 25_200,
  },
  {
    id: "grand_royal_campaign_blueprint",
    name: "Grand Royal Campaign Blueprint",
    cost: 1_650_000,
    requiredLevel: 87,
    category: "power_upgrade",
    effect: "0.006% chance per input to launch a legendary campaign worth 475,000 Influence.",
    expectedValuePerThousandInputs: 28_500,
  },
  {
    id: "aethernet_kingdom_news_license",
    name: "Aethernet Kingdom News License",
    cost: 2_000_000,
    requiredLevel: 90,
    category: "power_upgrade",
    effect: "0.005% chance per input to become Front Page News worth 650,000 Influence.",
    expectedValuePerThousandInputs: 32_500,
  },
  {
    id: "aethernet_data_core",
    name: "Aethernet Data Core",
    cost: 2_500_000,
    requiredLevel: 93,
    category: "power_upgrade",
    effect: "0.004% chance per input to trigger an Aethernet Surge worth 900,000 Influence.",
    expectedValuePerThousandInputs: 36_000,
  },
  {
    id: "royal_influence_exchange_charter",
    name: "Royal Influence Exchange Charter",
    cost: 3_100_000,
    requiredLevel: 96,
    category: "power_upgrade",
    effect: "0.0035% chance per input to move the royal markets worth 1,200,000 Influence.",
    expectedValuePerThousandInputs: 42_000,
  },
  {
    id: "crown_of_the_aethernet_algorithm_dragon",
    name: "Crown of the Aethernet Algorithm Dragon",
    cost: 4_000_000,
    requiredLevel: 99,
    category: "power_upgrade",
    effect:
      "0.003% chance per input to start an Aethernet trend cascade worth 1,750,000 Influence.",
    expectedValuePerThousandInputs: 52_500,
  },
];
